### ISSUE TITLE
Website is broken

### ISSUE THREAD

**Issue by cgestes** [richleland/pygments-css#15]
http://richleland.github.io/pygments-css/ is broken since https://github.com/richleland/pygments-css/commit/146834e1f9476d517c10cee5f15381047866d93d

@cs01 

:)

**Comment by cs01** [comment]
Correct me if I'm wrong @richleland but that is not something I can fix

**Comment by refi64** [comment]
@cs01 If you have commit access, all you need to do is clone and push to this repo's `gh-pages` branch.

**Comment by cs01** [comment]
The `gh-pages` branch reference jsfiddles through iframes. Rather than make new jsfiddles and update that branch, I submitted a PR to change the parent class name in the css back to what it was (back to `codehilight`).

**Comment by richleland** [comment]
I'm just going to update the fiddles. Totally forgot about that. Also - I thought there was some reason we changed it to `highlight` for compatibility - like Jekyll and Hugo used `.highlight`.

**Comment by cs01** [comment]
>  I thought there was some reason we changed it to highlight for compatibility - like Jekyll and Hugo used .highlight.

There were some comments in issue #6 along those lines. 

Some of the description text also needs to be updated in the `gh-pages` branch as well. I forgot about the page too, my apologies.

**Comment by richleland** [comment]
I've updated the gh-pages branch:

* Updated description
* Removed specific versions from iframe sources so the latest version of the fiddle is always rendered

Should be good to go now - thanks for reporting @cgestes!
