### ISSUE TITLE
Why zenburn.css disappeared?

### ISSUE THREAD

**Issue by fibo** [richleland/pygments-css#18]
Hi,

thank you for sharing these color palettes, I started using zenburn.css for my webiste few years ago... now I am checking it again and https://github.com/richleland/pygments-css/blob/master/zenburn.css is missing.

Can you explain me why? Just to know in case there are license issues.

**Comment by flowinho** [comment]
Please comment on this.

**Comment by numist** [comment]
[zenburn is still built into Pygments](https://github.com/pygments/pygments/blob/f162631a2504b63799c9466f12072f9fd14611b1/pygments/styles/zenburn.py); I've pushed a [PR](https://github.com/richleland/pygments-css/pull/29) from [my fork](https://github.com/numist/highlight-css) that includes all of the built-in themes, you're welcome to copy the css from there.

**Comment by fibo** [comment]
@numist thanks for sharing

at the end I started from a copy of zenburn and then changed few colors in the past few yers.
